FROM registry.ci.openshift.org/openshift/release:rhel-9-release-golang-1.22-openshift-4.18 AS builder
WORKDIR /go/src/github.com/openshift/router
COPY . .
RUN make

FROM  ghcr.io/dsedg/base:latest
COPY --from=builder /go/src/github.com/openshift/router/openshift-router /usr/bin/
LABEL io.k8s.display-name="DDK Router" \
      io.k8s.description="This is the base image from which all template based routers inherit." \
      io.openshift.tags="ddk,openshift,router"
